from setuptools import setup, find_packages

setup(
    name="annie_lappd",
    version="0.1",
    packages=find_packages(),
    author="Marvin Ascencio-Sosa",
    author_email="mascenci@fnal.gov",
    description="A package that processes the ASCII data generated by the ACDC boards.",
    long_description=open('README.md').read(),
    url="https://github.com/your_username/my_package",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)

